all: task1_1 task1_2 task2_1 task2_2

task1_1: task1_1.cu
	nvcc -o task1_1 task1_1.cu

task1_2: task1_2.cu
	nvcc -o task1_2 task1_2.cu

task2_1: task2_1.cu
	nvcc -o task2_1 task2_1.cu

task2_2: task2_2.cu
	nvcc -o task2_2 task2_2.cu

.PHONY: all
